//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazdirmaIslemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Muhafaza
    {
        public int ıd { get; set; }
        public string StokNo { get; set; }
        public string StokAdi { get; set; }
        public string barkod { get; set; }
    }
}
